import type { Event } from './types'

export const STATIC_EVENTS: Event[] = [
  {
    id: 'tabla-synths-3',
    title: 'Tabla & Synths · Vol. III',
    slug: 'tabla-synths-vol-iii',
    date: '2026-04-11',
    dateDisplay: 'Sat 11 Apr',
    startTime: '9pm',
    endTime: '4am',
    ageRestriction: '18+',
    venue: 'Phonox',
    address: '418 Brixton Rd, SW9 7AY',
    postcode: 'SW9',
    genre: 'bolly',
    lineup: ['Anish Kumar', 'Pri Singh', 'Amuse Residents'],
    priceFrom: 18,
    soldPercentage: 74,
    imageStyle: 'amber-tint',
    ticketTiers: [
      {
        id: 'eb',
        name: 'Early Bird',
        description: 'First release. Closes when sold out — usually inside the first 48 hours.',
        price: 18,
        fee: 1.20,
        tag: 'Final 14',
        tagStyle: 'amber',
      },
      {
        id: 'ga',
        name: 'General Admission',
        description: 'Standard entry. Doors from 9pm. Cloakroom included. Re-entry at door discretion.',
        price: 24,
        fee: 1.60,
        tag: 'Most popular',
        tagStyle: 'dark',
      },
      {
        id: 'lr',
        name: 'Late Release',
        description: 'Available from week-of. Same access as GA — priced honestly for last-minute dates.',
        price: 38,
        fee: 2.10,
      },
      {
        id: 'vip',
        name: 'Booth Access + Welcome Drink',
        description: 'Skip the queue. Booth wristband for the night. One welcome cocktail at the door.',
        price: 65,
        fee: 3.40,
        tag: 'VIP',
        tagStyle: 'dark',
      },
      {
        id: 'group6',
        name: 'Group of 6 Bundle',
        description: 'Six GA tickets at £20 each — saved for groups. Returned tomorrow at 12pm.',
        price: 120,
        fee: 0,
        soldOut: true,
        isSoldOutBundle: true,
      },
    ],
    lineupDetail: [
      { name: 'Anish Kumar', role: 'Headline · 90 min set', initials: 'AK', imageStyle: 'amber-tint' },
      { name: 'Pri Singh', role: 'Direct support · 75 min', initials: 'PS', imageStyle: 'default' },
      { name: 'Amuse Residents', role: 'Warm-up & close · b2b', initials: 'AR', imageStyle: 'dark' },
      { name: 'Live Tabla', role: 'Special guest · 30 min', initials: 'LT', imageStyle: 'default' },
    ],
    description: 'A South-Asian/electronic crossover night, three years deep. Live tabla, modular synths, Bollywood edits and a sound system rebuilt for it.',
  },
  {
    id: 'late-garden',
    title: 'Late Garden Sessions',
    date: '2026-05-02',
    dateDisplay: 'Fri 02 May',
    startTime: '8pm',
    endTime: '2am',
    ageRestriction: '18+',
    venue: 'Hoxton Yard',
    address: 'Shoreditch, E2',
    genre: 'house',
    lineup: ['Hannah Wants (B2B)', 'Maara', 'Lewis Boardman'],
    priceFrom: 24,
    soldPercentage: 42,
    imageStyle: 'dark',
    ticketTiers: [
      { id: 'eb', name: 'Early Bird', description: 'Limited early release at reduced price.', price: 20, fee: 1.40 },
      { id: 'ga', name: 'General Admission', description: 'Standard entry. Doors from 8pm.', price: 24, fee: 1.60, tag: 'Most popular', tagStyle: 'dark' },
      { id: 'vip', name: 'Outdoor Booth', description: 'Reserved outdoor booth with bottle service.', price: 55, fee: 2.90, tag: 'VIP', tagStyle: 'dark' },
    ],
  },
  {
    id: 'two-step-ukg',
    title: 'Two-Step Sundays · UKG Special',
    date: '2026-05-23',
    dateDisplay: 'Sat 23 May',
    startTime: '10pm',
    endTime: '4am',
    ageRestriction: '18+',
    venue: 'XOYO',
    address: 'Old Street, EC2A',
    genre: 'garage',
    lineup: ['Conducta', 'Salute', 'Holly Lester'],
    priceFrom: 20,
    soldPercentage: 18,
    imageStyle: 'default',
    ticketTiers: [
      { id: 'eb', name: 'Early Bird', description: 'First allocation — usually sells in 24 hours.', price: 16, fee: 1.00, tag: 'Available now', tagStyle: 'amber' },
      { id: 'ga', name: 'General Admission', description: 'Standard entry. Queue from 10pm.', price: 20, fee: 1.40 },
      { id: 'lr', name: 'Late Release', description: 'Last-minute pricing — same access as GA.', price: 28, fee: 1.80 },
    ],
  },
  {
    id: 'the-cut-hiphop',
    title: 'The Cut · 90s Hip-hop',
    date: '2026-06-06',
    dateDisplay: 'Sat 06 Jun',
    startTime: '10pm',
    endTime: '3am',
    ageRestriction: '18+',
    venue: 'The Cause',
    address: 'Tottenham, N17',
    genre: 'hiphop',
    lineup: ['Rampage Sound', 'DJ Snips', 'Manara'],
    priceFrom: 16,
    soldPercentage: 96,
    statusLabel: 'Last release',
    imageStyle: 'dark',
    ticketTiers: [
      { id: 'ga', name: 'General Admission', description: 'Final tickets — do not sleep on these.', price: 16, fee: 1.00, tag: 'Last few', tagStyle: 'amber' },
      { id: 'lr', name: 'Late Release', description: 'Last-minute addition. Same access as GA.', price: 22, fee: 1.50 },
    ],
  },
  {
    id: 'bolly-pop-pride',
    title: 'Bolly Pop · Pride Edition',
    date: '2026-06-19',
    dateDisplay: 'Fri 19 Jun',
    startTime: '9pm',
    endTime: '3am',
    ageRestriction: '18+',
    venue: 'Heaven',
    address: 'Charing Cross, WC2N',
    genre: 'bolly',
    lineup: ['DJ Ritu', 'Nikita Gandhi', 'Amuse Residents'],
    priceFrom: 22,
    soldPercentage: 55,
    imageStyle: 'amber-tint',
    ticketTiers: [
      { id: 'eb', name: 'Early Bird', description: 'Pride special pricing. Limited allocation.', price: 18, fee: 1.20, tag: 'Pride rate', tagStyle: 'amber' },
      { id: 'ga', name: 'General Admission', description: 'Standard entry. Glitter at the door.', price: 22, fee: 1.60, tag: 'Most popular', tagStyle: 'dark' },
      { id: 'vip', name: 'VIP Balcony', description: 'Balcony access + one welcome cocktail.', price: 45, fee: 2.50, tag: 'VIP', tagStyle: 'dark' },
    ],
  },
  {
    id: 'sunset-rooftop-6',
    title: 'Sunset Rooftop · Vol. VI',
    date: '2026-07-04',
    dateDisplay: 'Sat 04 Jul',
    startTime: '4pm',
    endTime: '11pm',
    ageRestriction: '18+',
    venue: 'Netil 360',
    address: 'London Fields, E8',
    genre: 'house',
    lineup: ['Folamour', 'Shanti Celeste', 'Tash LC'],
    priceFrom: 28,
    soldPercentage: 88,
    imageStyle: 'default',
    ticketTiers: [
      { id: 'ga', name: 'General Admission', description: 'Open-air rooftop. Sunglasses required.', price: 28, fee: 1.80, tag: 'Final wave', tagStyle: 'amber' },
      { id: 'vip', name: 'Rooftop Booth', description: 'Reserved table for 4, bottle of prosecco included.', price: 90, fee: 4.50, tag: 'VIP', tagStyle: 'dark' },
    ],
  },
]
